name: connectivity_validator
description: "A Flutter package that provides validated internet connectivity status."
version: 0.1.0
homepage: https://github.com/sabeelmuttil/connectivity_validator
# author: Sabeel KM

environment:
  sdk: ^3.10.7
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.connectivity_validator
        pluginClass: ConnectivityValidatorPlugin
      ios:
        pluginClass: ConnectivityValidatorPlugin
