name: connectivity_validator
description: "A robust internet connectivity checker that validates actual network access using native Android (NET_CAPABILITY_VALIDATED) and iOS (NWPathMonitor) APIs."
version: 0.0.4
homepage: https://github.com/sabeelmuttil/connectivity_validator
repository: https://github.com/sabeelmuttil/connectivity_validator

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.skm.connectivity_validator
        pluginClass: ConnectivityValidatorPlugin
      ios:
        pluginClass: ConnectivityValidatorPlugin
